

server:
  port: 8081
spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-classname: ${db.driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: jobs
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  config:
    import: configserver:http://localhost:8086/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DB_HOST:localhost}:8761/eureka/
    enabled: true