version: '3'  # Specify the Docker Compose file version

services:    # Define the services (containers)
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=linkedin-clone
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
