

server:
  port: 8080

spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-classname: ${db.driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-provider
          uri: lb://IDENTITY-PROVIDER
          predicates:
            - Path=/api/v1/auth/**

        - id: transfer
          uri: lb://TRANSFER
          predicates:
            - Path=/api/v1/transfer/**
          filters:
            - AuthenticationFilter

        - id: notifications
          uri: lb://NOTIFICATIONS
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter

        - id: customers
          uri: lb://CUSTOMERS
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter
  config:
    import: configserver:http://localhost:8081/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DB_HOST:localhost}:8761/eureka/
    enabled: true