spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/e-banking
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: IDENTITY-PROVIDER
server:
  port: 8081

bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000