server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    gateway:
      routes:
        - id : TRANSFER-SERVICE
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/api/v1/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: TRANSFER-SERVICE
                fallbackuri: forward:/transferServiceFallBack

        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/v1/client/**
          filters:
            - name: CircuitBreaker
              args:
                name: CLIENT-SERVICE
                fallbackuri: forward:/clientServiceFallBack

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: NOTIFICATION-SERVICE
                fallbackuri: forward:/notificationServiceFallBack

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  zipkin:
    baseUrl: http://zipkin-svc:9411

debug: true