server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9298}
  cloud:
    gateway:
      routes:
        - id : TRANSFER-SERVICE
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/api/v1/order/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: TRANSFER-SERVICE
                fallbackuri: forward:/transferServiceFallBack

        - id: IDENTITY-PROVIDER
          uri: lb://IDENTITY-PROVIDER
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: IDENTITY-PROVIDER
                fallbackuri: forward:/transferServiceFallBack

        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/v1/client/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: CLIENT-SERVICE
                fallbackuri: forward:/clientServiceFallBack

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: NOTIFICATION-SERVICE
                fallbackuri: forward:/notificationServiceFallBack

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka
logging:
  level:
    com.netflix.eureka: DEBUG
