server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
     gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # This applies the CORS configuration to all routes
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id : TRANSFER-SERVICE
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/api/transfers/**
          filters:
            - name: CircuitBreaker
              args:
                name: TRANSFER-SERVICE
                fallbackuri: forward:/transferServiceFallBack

        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/**
          filters:
            - name: CircuitBreaker
              args:
                name: CLIENT-SERVICE
                fallbackuri: forward:/clientServiceFallBack

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: NOTIFICATION-SERVICE
                fallbackuri: forward:/notificationServiceFallBack

