
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${DB_HOST:localhost}:8761/eureka/
spring:
  application:
    name: eureka-server
  config:
    import: configserver:http://localhost:8086/
server:
  port: 8761

